//+------------------------------------------------------------------+
//| TimerEngine.mqh                                                  |
//| REV 21 - scheduler / workload governor                           |
//|                                                                  |
//| Architecture for this revision:                                 |
//|   - ONE native MQL5 heartbeat (15 ms default).                   |
//|   - ONE global work budget for the whole heartbeat.              |
//|   - Software tiers have release intervals, not separate timers. |
//|   - OnTick only overwrites the latest market snapshot.           |
//|   - OnTradeTransaction only queues compact event data.           |
//|   - The scheduler consumes events and creates bounded work.      |
//|   - Cleanup can send several async requests, then WAIT.          |
//|   - The cycle is finished only after the required live state is  |
//|     confirmed by reconciliation.                                 |
//+------------------------------------------------------------------+
#ifndef TIMER_ENGINE_MQH
#define TIMER_ENGINE_MQH

#include "../Inputs.mqh"
#include "../Models/GridState.mqh"
#include "../Utils/TradeUtils.mqh"
#include "../Utils/MathUtils.mqh"
#include "../Utils/DebugLogger.mqh"
#include "../Utils/HistoryLogger.mqh"
#include "../Utils/BarUtils.mqh"
#include "../Utils/SessionFilter.mqh"
#include "../Utils/CloseOrderUtils.mqh"
#include "../Engines/OrderMonitor.mqh"
#include "../Engines/GridBuilder.mqh"
#include "../Engines/GridUpdater.mqh"
//#include "../Engines/ShiftingEngine.mqh"
#include "../Engines/SLManager.mqh"
//#include "../Engines/Recentering.mqh"
#include "../Engines/CleanupReset.mqh"

//+------------------------------------------------------------------+
//| Latest tick snapshot.                                            |
//| Price is deliberately OVERWRITTEN, never queued: old price       |
//| samples have no value once a newer market snapshot exists.       |
//+------------------------------------------------------------------+
MqlTick g_latestTick;
bool    g_latestTickValid = false;

//+------------------------------------------------------------------+
//| Transaction queue. Unlike price, transactions are LOSSLESS data  |
//| and therefore remain queued until classified by the scheduler.   |
//| The queue uses a head index so normal consumption does not shift  |
//| the whole array on every event.                                  |
//+------------------------------------------------------------------+
MqlTradeTransactionShort g_txQueue[];
int  g_txHead = 0;
bool g_txDirty = false;

//+------------------------------------------------------------------+
//| Fill work is intentionally separated from transaction ingestion. |
//| A DEAL_ADD only creates a work item; the fill reaction is then    |
//| executed in scheduler stages instead of inside OnTradeTransaction|
//| itself.                                                            |
//+------------------------------------------------------------------+
struct FillWorkItem
  {
   ulong dealTicket;
   ulong positionTicket;
  };

FillWorkItem g_fillQueue[];
int          g_fillHead = 0;
bool         g_fillActive = false;
FillWorkItem g_activeFill;
int          g_activeFillStage = 0;

// Pending cleanup trigger generated by a confirmed deal-out event.
bool g_cleanupTriggerPending = false;

// Medium reconciliation is raised by trade activity, but remains a
// scheduled task so a burst of transactions cannot recursively scan.
bool g_reconcilePending = true;

// Scheduler release timestamps. There is only ONE real MQL5 timer.
ulong g_lastFastMs       = 0;
ulong g_lastMediumMs     = 0;
ulong g_lastSlowMs       = 0;
ulong g_lastBackgroundMs = 0;
ulong g_lastSessionMs    = 0;

// Small scheduler diagnostics. They do not drive strategy decisions.
ulong g_lastFrameStartUs = 0;
ulong g_lastFrameWorkUs  = 0;
ulong g_maxFrameWorkUs   = 0;
ulong g_lastTierWorkUs[5] = {0,0,0,0,0};

enum SchedulerTier
  {
   TIER_TRANSACTIONS = 0,
   TIER_CLEANUP      = 1,
   TIER_FAST         = 2,
   TIER_MEDIUM       = 3,
   TIER_SLOW         = 4
  };

//+------------------------------------------------------------------+
//| Basic scheduler timing helpers                                   |
//+------------------------------------------------------------------+
ulong SchedulerNowMs()
  {
   return GetTickCount64();
  }

bool SchedulerBudgetAvailable(ulong frameStartUs, ulong budgetUs)
  {
   return (GetMicrosecondCount() - frameStartUs) < budgetUs;
  }

bool SchedulerTierDue(ulong nowMs, ulong &lastRunMs, ulong intervalMs)
  {
   if(intervalMs == 0)
      return true;

   if((nowMs - lastRunMs) < intervalMs)
      return false;

   // Advance from the current time, not by repeated catch-up periods.
   // This prevents a delayed terminal from creating a burst of catch-up work.
   lastRunMs = nowMs;
   return true;
  }

void SchedulerRecordTierWork(int tier, ulong startUs)
  {
   if(tier < 0 || tier >= 5) return;
   ulong used = GetMicrosecondCount() - startUs;
   g_lastTierWorkUs[tier] = used;
  }

//+------------------------------------------------------------------+
//| Transaction queue append                                         |
//+------------------------------------------------------------------+
void QueueTransaction(const MqlTradeTransactionShort &item)
  {
   int size = ArraySize(g_txQueue);
   if(ArrayResize(g_txQueue, size + 1, 128) != size + 1)
     {
      // A transaction must never be silently discarded. If the terminal
      // cannot grow our queue, keep the dirty flag and report the fault.
      g_txDirty = true;
      LogDebug("[Scheduler] CRITICAL: transaction queue resize failed.");
      return;
     }

   g_txQueue[size] = item;
   g_txDirty = true;
  }

//+------------------------------------------------------------------+
//| Fill queue append                                                |
//+------------------------------------------------------------------+
void QueueFillWork(ulong dealTicket, ulong positionTicket)
  {
   int size = ArraySize(g_fillQueue);
   if(ArrayResize(g_fillQueue, size + 1, 32) != size + 1)
     {
      LogDebug("[Scheduler] CRITICAL: fill work queue resize failed.");
      return;
     }

   g_fillQueue[size].dealTicket     = dealTicket;
   g_fillQueue[size].positionTicket = positionTicket;
  }

//+------------------------------------------------------------------+
//| Remove already-consumed queue prefixes without doing it per item.|
//+------------------------------------------------------------------+
void CompactTransactionQueue()
  {
   int total = ArraySize(g_txQueue);
   if(g_txHead <= 0) return;

   if(g_txHead >= total)
     {
      ArrayFree(g_txQueue);
      g_txHead = 0;
      g_txDirty = false;
      return;
     }

   // Compact only after a meaningful prefix has been consumed.
   if(g_txHead < 32 && g_txHead < total / 2)
      return;

   int remaining = total - g_txHead;
   for(int i = 0; i < remaining; i++)
      g_txQueue[i] = g_txQueue[g_txHead + i];

   ArrayResize(g_txQueue, remaining);
   g_txHead = 0;
  }

void CompactFillQueue()
  {
   int total = ArraySize(g_fillQueue);
   if(g_fillHead <= 0) return;

   if(g_fillHead >= total)
     {
      ArrayFree(g_fillQueue);
      g_fillHead = 0;
      return;
     }

   if(g_fillHead < 16 && g_fillHead < total / 2)
      return;

   int remaining = total - g_fillHead;
   for(int i = 0; i < remaining; i++)
      g_fillQueue[i] = g_fillQueue[g_fillHead + i];
   ArrayResize(g_fillQueue, remaining);
   g_fillHead = 0;
  }

//+------------------------------------------------------------------+
//| Transaction classification                                       |
//| IMPORTANT: no strategy engine is called here.                   |
//| This function only converts immutable event data into pending    |
//| work/flags. Actual strategy work happens in later tiers.         |
//+------------------------------------------------------------------+
bool ProcessTransactionQueue(ulong frameStartUs, ulong budgetUs, GridState &state)
  {
   int total = ArraySize(g_txQueue);
   int processed = 0;

   while(g_txHead < total)
     {
      if(!SchedulerBudgetAvailable(frameStartUs, budgetUs))
         return false;
      if(processed >= InpSchedulerMaxTransactionsPerFrame)
         return false;

      MqlTradeTransactionShort tx = g_txQueue[g_txHead];

      if(tx.type == TRADE_TRANSACTION_REQUEST)
        {
         // Only REQUEST transactions carry the request/result pair. The
         // request_id is the correlation key for async cleanup requests.
         CleanupHandleRequestResult(state, tx.requestId, tx.retcode);
        }
      else if(tx.type == TRADE_TRANSACTION_DEAL_ADD)
        {
         if(tx.deal == 0)
           {
            // Nothing useful to classify; retain the event as consumed data.
            g_txHead++;
            processed++;
            continue;
           }

         // DEAL_ENTRY is only available through deal history. This lookup is
         // done here (scheduler context), NEVER in OnTradeTransaction().
         
         //if(!HistoryDealSelect(tx.deal))
         //   return false; // keep the event for a later retry
            
         if(!HistoryDealSelect(tx.deal))
           {
            // Do NOT block the queue on a temporarily unavailable history record.
            // Re-append the same immutable transaction at the tail, consume its
            // current head slot, and continue with unrelated events behind it.
            // `total` is the queue size captured at frame start, so the re-appended
            // item cannot be retried again in this same frame. Compacting below
            // retains it for a later heartbeat. This prevents head-of-line blocking
            // while keeping the transaction lossless.
            QueueTransaction(tx);
            g_txHead++;
            processed++;
            continue;
           }

         long magic = HistoryDealGetInteger(tx.deal, DEAL_MAGIC);
         if(magic == state.magicNumber)
           {
            ENUM_DEAL_ENTRY entry = (ENUM_DEAL_ENTRY)HistoryDealGetInteger(tx.deal, DEAL_ENTRY);
            UpdateSideVolumeAggregate(state, tx.dealType, entry, tx.volume, tx.price);

            if(entry == DEAL_ENTRY_IN)
              {
               // Once cleanup owns the cycle, a newly-created position must be
               // treated as account state to be cleaned, NOT as a new strategy
               // fill. This prevents a late fill transaction from reviving the
               // just-finished cycle.
               if(!state.cleanupInProgress)
                  QueueFillWork(tx.deal, tx.position);
               else
                  g_reconcilePending = true;
              }
            else if(entry == DEAL_ENTRY_OUT ||
                    entry == DEAL_ENTRY_INOUT ||
                    entry == DEAL_ENTRY_OUT_BY)
              {
               if(!state.cleanupInProgress &&
                  !CleanupWasOurPosition(state, tx.position))
                  g_cleanupTriggerPending = true;
               else
                  g_reconcilePending = true;
              }
           }

         g_reconcilePending = true;
        }
      else if(tx.type == TRADE_TRANSACTION_ORDER_ADD ||
              tx.type == TRADE_TRANSACTION_ORDER_UPDATE ||
              tx.type == TRADE_TRANSACTION_ORDER_DELETE ||
              tx.type == TRADE_TRANSACTION_POSITION)
        {
         // Do not scan here. Just wake the appropriate reconciliation worker.
         g_reconcilePending = true;
        }

      g_txHead++;
      processed++;
     }

   CompactTransactionQueue();
   return true;
  }

//+------------------------------------------------------------------+
//| Invalidate queued/active fill reactions when cleanup takes over.  |
//| Transaction facts remain queued for audit/classification; only    |
//| strategy reactions for the old cycle are discarded.               |
//+------------------------------------------------------------------+
void ClearPendingFillWork()
  {
   ArrayFree(g_fillQueue);
   g_fillHead = 0;
   g_fillActive = false;
   g_activeFillStage = 0;
  }

//+------------------------------------------------------------------+
//| Execute one fill reaction as a resumable state machine.          |
//| This preserves the original order of the strategy reactions while|
//| allowing the scheduler to stop between stages if its budget ends.|
//+------------------------------------------------------------------+
bool ProcessFillWork(ulong frameStartUs, ulong budgetUs, GridState &state)
  {
   if(state.cleanupInProgress)
     {
      // A cleanup owns the cycle. Pending fill reactions from the old cycle
      // must not mutate strategy state after cleanup has begun.
      return true;
     }

   while(SchedulerBudgetAvailable(frameStartUs, budgetUs))
     {
      if(!g_fillActive)
        {
         if(g_fillHead >= ArraySize(g_fillQueue))
           {
            CompactFillQueue();
            return true;
           }

         g_activeFill      = g_fillQueue[g_fillHead];
         g_activeFillStage = 0;
         g_fillActive      = true;
        }

      switch(g_activeFillStage)
        {
         case 0:
            // A position can disappear between DEAL_ADD capture and queued
            // processing. In that case the event is historical data, not a
            // reason to mutate strategy state.
            if(!PositionSelectByTicket(g_activeFill.positionTicket))
              {
               g_fillHead++;
               g_fillActive = false;
               g_activeFillStage = 0;
               CompactFillQueue();
               continue;
              }
            ProcessOrderFill(g_activeFill.positionTicket, state);
            g_activeFillStage++;
            break;

         case 1:
            ReSnapshotIfArmed(state);
            g_activeFillStage++;
            break;

         case 2:
            UpdateOppositeGrid(state);
            g_activeFillStage++;
            break;

         case 3:
            //ShiftGrid(state);
            //g_activeFillStage++;
            break;

         case 4:
            ProcessInsideStrategy(state);
            g_activeFillStage++;
            break;

         case 5:
            // Matches the original OnTradeTransaction behavior: outside
            // refill is only flagged here and actually executed by a later
            // scheduled task.
            state.outsideRefillPending = true;
            g_activeFillStage++;
            break;

         case 6:
            // Basket profit is normally refreshed by the fast tier before SL
            // work. This call preserves the original post-fill SL check.
            CalculateBasketProfits(state);
            ProcessSLManager(state);
            g_activeFillStage++;
            break;

         case 7:
            LogHistory("ORDER_FILL",
                       state.lastHitPrice,
                       state.lastHitDirection==ORDER_TYPE_BUY ? "BUY" : "SELL",
                       state.lastHitLot,
                       state.passCounter,
                       state.currentBlockLot,
                       state.basketProfit,
                       state.sessionAllowed,
                       AccountInfoDouble(ACCOUNT_MARGIN_FREE));
            g_activeFillStage++;
            break;

         default:
            g_fillHead++;
            g_fillActive = false;
            g_activeFillStage = 0;
            CompactFillQueue();
            break;
        }
     }

   return false; // budget exhausted; resume on a later heartbeat
  }

//+------------------------------------------------------------------+
//| Session cache. Session boundaries are minute based, so evaluating |
//| them every tick has no value.                                   |
//+------------------------------------------------------------------+
void ProcessSessionTask(ulong nowMs, GridState &state)
  {
   if((nowMs - g_lastSessionMs) < (ulong)InpSessionCheckIntervalMs)
      return;

   g_lastSessionMs = nowMs;

   bool previous = state.sessionAllowed;
   state.sessionAllowed = IsSessionAllowed();

   if(!previous && state.sessionAllowed)
      LogSessionChange(true, GetActiveSessionName());
   else if(previous && !state.sessionAllowed)
      LogSessionChange(false, "Session ended");
  }

//+------------------------------------------------------------------+
//| Fast strategy tier                                               |
//+------------------------------------------------------------------+
void ExecuteFastTasks(ulong frameStartUs, ulong budgetUs, ulong nowMs, GridState &state)
  {
   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs)) return;

   if(SchedulerTierDue(nowMs, g_lastFastMs, (ulong)InpFastTierIntervalMs))
     {
      ulong tierStart = GetMicrosecondCount();

      ProcessSessionTask(nowMs, state);

      // Basket data is current-state data, not an event queue. Refresh it at
      // the fast tier cadence so SL logic does not scan on every incoming tick.
      if(!state.cleanupInProgress && state.cycleActive)
         CalculateBasketProfits(state);

      if(!state.cleanupInProgress)
         ProcessFillWork(frameStartUs, budgetUs, state);

      // The fill state machine may have consumed part of the budget. Recheck
      // before starting another potentially expensive SL search.
      if(SchedulerBudgetAvailable(frameStartUs, budgetUs) &&
         !state.cleanupInProgress && state.cycleActive)
         ProcessSLManager(state);

      SchedulerRecordTierWork(TIER_FAST, tierStart);
     }
  }

//+------------------------------------------------------------------+
//| Medium-tier structural work                                     |
//+------------------------------------------------------------------+
void ExecuteMediumTasks(ulong frameStartUs, ulong budgetUs, ulong nowMs, GridState &state)
  {
   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs)) return;

   if(!SchedulerTierDue(nowMs, g_lastMediumMs, (ulong)InpMediumTierIntervalMs))
      return;

   ulong tierStart = GetMicrosecondCount();

   ProcessSessionTask(nowMs, state);
   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs))
     {
      SchedulerRecordTierWork(TIER_MEDIUM, tierStart);
      return;
     }

   // Structural reconciliation is deliberately separate from transaction
   // ingestion. It asks the terminal what exists NOW.
   if(state.cleanupInProgress)
     {
      // CleanupEngine owns cleanup reconciliation; do not interfere here.
     }
   else
     {
      if(g_reconcilePending || state.gridPlaced || state.cycleActive)
        {
         int posCount = CountPositions(state.magicNumber);
         int ordCount = CountOrders(state.magicNumber);

         // A grid flag with no live broker state is a stale local state shape.
         if(state.gridPlaced && !state.cycleActive && posCount == 0 && ordCount == 0)
            ResetGridBuilder(state);

         // An armed wall with no active cycle is stale local protection state.
         if(state.slWallArmed && !state.cycleActive)
            ResetSLManager(state);

         g_reconcilePending = false;
        }
     }

   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs))
     {
      SchedulerRecordTierWork(TIER_MEDIUM, tierStart);
      return;
     }

   // Grid build, recentering and fresh-grid verification retain the original
   // strategy conditions; only their execution frequency has moved into the
   // scheduler.
   if(!state.cleanupInProgress)
     {
      CheckAndBuildGrid(state);

      if(state.needsGridVerification)
        {
         state.needsGridVerification = false;
         if(!VerifyFreshGrid(state))
           {
            LogDebug("[Coordinator] Fresh grid failed verification — resetting.");
            TriggerSafetyStop(state, "GRID_VERIFICATION_FAILED");
           }
        }

      //if(!state.cleanupInProgress && ProcessRecentering(state))
      //   BuildGrid(SymbolInfoDouble(_Symbol, SYMBOL_BID), state);

      if(!state.cleanupInProgress && state.outsideRefillPending)
        {
         RefillOutside(state);
         state.outsideRefillPending = false;
        }

      if(!state.cleanupInProgress && state.refillNeeded)
        {
         ProcessInsideMaintenance(state);
         state.refillNeeded = false;
        }
     }

   SchedulerRecordTierWork(TIER_MEDIUM, tierStart);
  }

//+------------------------------------------------------------------+
//| Slow dashboard tier                                             |
//+------------------------------------------------------------------+
void ExecuteSlowTasks(ulong frameStartUs, ulong budgetUs, ulong nowMs, GridState &state)
  {
   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs)) return;
   if(!SchedulerTierDue(nowMs, g_lastSlowMs, (ulong)InpTimerIntervalSec * (ulong)1000)) return;

   ulong tierStart = GetMicrosecondCount();
   if(InpShowDashboard)
      UpdateDashboard(state);
   // Dashboard/statistics remain here rather than in the high-frequency path.
   SchedulerRecordTierWork(TIER_SLOW, tierStart);
  }

//+------------------------------------------------------------------+
//| Background tier                                                  |
//+------------------------------------------------------------------+
void ExecuteBackgroundTasks_old(ulong frameStartUs, ulong budgetUs, ulong nowMs, GridState &state)
  {
   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs)) return;
   if(!SchedulerTierDue(nowMs, g_lastBackgroundMs, (ulong)InpBackgroundTierIntervalMs)) return;

   ulong tierStart = GetMicrosecondCount();
   // Deliberately light in this first scheduler revision. File/history work
   // is not allowed to become a surprise CPU burst during volatile trading.
   SchedulerRecordTierWork(TIER_SLOW, tierStart);
  }
  
void ExecuteBackgroundTasks(ulong frameStartUs, ulong budgetUs, ulong nowMs, GridState &state)
{
   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs)) return;
   if(!SchedulerTierDue(nowMs, g_lastBackgroundMs, (ulong)InpBackgroundTierIntervalMs)) return;

   ulong tierStart = GetMicrosecondCount();

   if(state.safetyAlertPending &&
      !state.safetyStopPending &&
      !state.cleanupInProgress)
     {
      string summary = StringFormat(
         "HedgeGrid SAFETY STOP\nSymbol: %s\nReason: %s\nCleanup confirmed complete\nTime: %s",
         _Symbol,
         state.safetyStopReason,
         TimeToString(TimeCurrent(), TIME_DATE|TIME_SECONDS));

      LogDebug("[SafetyNet] " + summary);
      SendTelegramMessage(summary);

      state.safetyAlertPending = false;
      state.safetyStopReason   = "";
     }

   SchedulerRecordTierWork(TIER_SLOW, tierStart);
}
//+------------------------------------------------------------------+
//| Start/finish scheduler runtime                                  |
//+------------------------------------------------------------------+
void InitSchedulerRuntime()
  {
   ulong now = SchedulerNowMs();

   g_txHead = 0;
   g_txDirty = (ArraySize(g_txQueue) > 0);
   g_fillHead = 0;
   g_fillActive = false;
   g_activeFillStage = 0;
   g_cleanupTriggerPending = false;
   g_reconcilePending = true;

   // First execution of each tier is allowed promptly after OnInit.
   g_lastFastMs       = (now >= (ulong)InpFastTierIntervalMs) ? now - (ulong)InpFastTierIntervalMs : 0;
   g_lastMediumMs     = (now >= (ulong)InpMediumTierIntervalMs) ? now - (ulong)InpMediumTierIntervalMs : 0;
   g_lastSlowMs       = (now >= (ulong)InpTimerIntervalSec*(ulong)1000) ? now - (ulong)InpTimerIntervalSec*(ulong)1000 : 0;
   g_lastBackgroundMs = now;
   g_lastSessionMs    = 0;
  }

void ShutdownSchedulerRuntime()
  {
   ArrayFree(g_txQueue);
   ArrayFree(g_fillQueue);
   g_txHead = 0;
   g_fillHead = 0;
   g_fillActive = false;
  }

//+------------------------------------------------------------------+
//| The single scheduler entry point.                               |
//| Priority order is: transactions → cleanup → fast → medium →    |
//| slow/background. Cleanup priority never means unlimited CPU; all |
//| work shares one frame budget.                                    |
//+------------------------------------------------------------------+
void RunScheduler(GridState &state)
  {
   ulong frameStartUs = GetMicrosecondCount();
   ulong nowMs = SchedulerNowMs();
   ulong budgetUs = (ulong)MathMax(0, InpSchedulerBudgetMs) * (ulong)1000;

   g_lastFrameStartUs = frameStartUs;

   // If a zero budget is configured, still perform zero heavy work. This is
   // intentional: configuration, not a hidden fallback, controls the engine.
   if(budgetUs == 0)
      return;

   // 1) LOSSLESS transaction classification. No strategy engine is called.
   if(g_txDirty && SchedulerBudgetAvailable(frameStartUs, budgetUs))
     {
      ulong tierStart = GetMicrosecondCount();
      ProcessTransactionQueue(frameStartUs, budgetUs, state);
      SchedulerRecordTierWork(TIER_TRANSACTIONS, tierStart);
     }

   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs))
      return;

   if(state.safetyStopPending)
   {
      if(!state.cleanupInProgress)
      {
         StartCleanupSequence(state, CLEANUP_CLOSE_ALL);
         ClearPendingFillWork();
      }
      else
      {
         // Safety stop always escalates an existing cleanup to FULL cleanup.
         state.cleanupType = CLEANUP_CLOSE_ALL;
      }
   
      // Safety cleanup supersedes any normal cleanup trigger.
      g_cleanupTriggerPending = false;
      state.safetyStopPending = false;
   }

   // A close event is converted into cleanup state before any opening or
   // modifying work can run. Pending fill reactions are discarded when the
   // cleanup state actually starts (see StartCleanupSequence()).
   if(g_cleanupTriggerPending && !state.cleanupInProgress)
     {
      StartCleanupSequence(state, InpCleanupMode);
      ClearPendingFillWork();
      g_cleanupTriggerPending = false;
     }

   // 2) Cleanup / account safety. This tier may send several async requests,
   // but each request returns immediately and remains tracked until the
   // account state confirms completion.
   if((state.cleanupInProgress || g_cleanupTriggerPending) &&
      SchedulerBudgetAvailable(frameStartUs, budgetUs))
     {
      ulong tierStart = GetMicrosecondCount();
      ProcessCleanupWork(frameStartUs, budgetUs, state);
      SchedulerRecordTierWork(TIER_CLEANUP, tierStart);
     }

   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs))
      return;

   // 3) Fast market/strategy tier. Disabled while cleanup owns the cycle.
   ExecuteFastTasks(frameStartUs, budgetUs, nowMs, state);

   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs))
      return;

   // 4) Medium structural tier.
   ExecuteMediumTasks(frameStartUs, budgetUs, nowMs, state);

   if(!SchedulerBudgetAvailable(frameStartUs, budgetUs))
      return;

   // 5) Slow/background work.
   ExecuteSlowTasks(frameStartUs, budgetUs, nowMs, state);
   if(SchedulerBudgetAvailable(frameStartUs, budgetUs))
      ExecuteBackgroundTasks(frameStartUs, budgetUs, nowMs, state);

   g_lastFrameWorkUs = GetMicrosecondCount() - frameStartUs;
   if(g_lastFrameWorkUs > g_maxFrameWorkUs)
      g_maxFrameWorkUs = g_lastFrameWorkUs;
  }

#endif
