#include "mt5_mock.hpp"
#include "ea_under_test.hpp"
#include <functional>
int passed=0;
void fresh(GridState &s){orders.clear();positions.clear();historyOrders.clear();historyDeals.clear();sends.clear();connected=true;tradeAllowed=true;sendOK=true;selectedOrder=selectedPosition=-1;mock_ms=1000;mock_us=1000000;nextRequest=1;s=GridState{};ResetGridState(s);s.magicNumber=77;InitScheduler30();InpEnableDebugLog=false;InpCleanupAsyncBatch=3;}
void tick(ulong ms=500){mock_ms+=ms;mock_us+=ms*1000;}
void process(GridState &s){ProcessPendingActions(s,GetMicrosecondCount(),15000);}
TransactionItem result(uint request,int code,ulong order=0){TransactionItem t;ResetTransactionItem(t);t.type=TRADE_TRANSACTION_REQUEST;t.symbol=_Symbol;t.requestMagic=77;t.requestId=request;t.retcode=code;t.resultOrder=order;return t;}
TransactionItem deal(ulong t,ulong pos){TransactionItem v;ResetTransactionItem(v);v.type=TRADE_TRANSACTION_DEAL_ADD;v.symbol=_Symbol;v.dealTicket=t;v.positionTicket=pos;return v;}
void check(const char *name,std::function<void()> body){body();passed++;std::cout<<"PASS "<<name<<"\n";}
int main(){
check("request guards preserve every command parameter in both waiting states",[]{GridState s;fresh(s);orders.push_back(Order{100});positions.push_back(Position{900,101});ReconcileTradeItems(s);for(auto status:{ACTION_WAIT_RESULT,ACTION_WAIT_CONFIRM}){for(auto &v:s.items){v.actionStatus=status;v.requestId=9;v.requestedSL=91;v.replaceAfterDelete=true;v.replacementPrice=104;}auto a=s.items;assert(!RequestDeleteOrder(s,100));assert(!RequestReplaceOrder(s,100,105,2));assert(!RequestClosePosition(s,900));assert(!RequestModifySL(s,900,89));for(int i=0;i<ArraySize(s.items);i++){assert(s.items[i].actionStatus==a[i].actionStatus);assert(s.items[i].requestId==9);assert(s.items[i].requestedSL==91);assert(s.items[i].replacementPrice==104);assert(s.items[i].replaceAfterDelete);}}});
check("all six REQUEST/ORDER/DEAL arrival permutations map one full fill",[]{std::vector<int> seq={0,1,2};do{GridState s;fresh(s);uint id=RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1,0,0,7);process(s);uint req=s.items[0].requestId;Order h{100};h.status=ORDER_STATE_FILLED;historyOrders[100]=h;positions.push_back(Position{900,100});historyDeals[500]=Deal{500,100,100};auto r=result(req,TRADE_RETCODE_DONE,100);auto d=deal(500,900);TransactionItem o;ResetTransactionItem(o);o.type=TRADE_TRANSACTION_ORDER_DELETE;o.orderTicket=100;for(int e:seq){if(e==0)HandleTransaction(s,r);if(e==1)HandleTransaction(s,o);if(e==2)assert(HandleTransaction(s,d));}ReconcileTradeItems(s);assert(ArraySize(s.items)==1);assert(s.items[0].id==id);assert(s.items[0].kind==ITEM_POSITION);assert(s.items[0].lastDealTicket==500);assert(s.items[0].level==7);assert(s.items[0].action==ACTION_NONE);assert(sends.size()==1);}while(std::next_permutation(seq.begin(),seq.end()));});
check("request acknowledgement is not completion and never consumes the deal",[]{GridState s;fresh(s);RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1);process(s);auto r=result(s.items[0].requestId,TRADE_RETCODE_PLACED,100);HandleRequestTransaction(s,r);assert(s.items[0].actionStatus==ACTION_WAIT_CONFIRM);assert(s.items[0].lastDealTicket==0);ReconcileTradeItems(s);assert(s.items[0].actionStatus==ACTION_WAIT_CONFIRM);process(s);assert(sends.size()==1);});
check("partial entry keeps remainder and position; final fill preserves in-flight SL",[]{GridState s;fresh(s);RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1,0,0,4);process(s);uint placeReq=s.items[0].requestId;Order o{100};o.volume=.6;orders.push_back(o);positions.push_back(Position{900,100,.4});historyDeals[500]=Deal{500,100,100,DEAL_ENTRY_IN,.4};auto d=deal(500,900);assert(HandleDealTransaction(s,d));auto placeResult=result(placeReq,TRADE_RETCODE_PLACED,100);HandleRequestTransaction(s,placeResult);assert(ArraySize(s.items)==2);assert(CountBookOrders(s)==1&&CountBookPositions(s)==1);int pos=FindItemByPositionTicket(s,900);assert(s.items[pos].level==4);ReconcileTradeItems(s);assert(RequestModifySL(s,900,90));process(s);pos=FindItemByPositionTicket(s,900);uint req=s.items[pos].requestId;orders.clear();o.status=ORDER_STATE_FILLED;historyOrders[100]=o;positions[0].volume=1;historyDeals[501]=Deal{501,100,100,DEAL_ENTRY_IN,.6};d=deal(501,900);HandleDealTransaction(s,d);assert(ArraySize(s.items)==1);assert(s.items[0].action==ACTION_MODIFY_SL&&s.items[0].requestId==req);assert(s.items[0].actionStatus==ACTION_WAIT_RESULT);positions[0].sl=90;ReconcileTradeItems(s);assert(s.items[0].actionStatus==ACTION_WAIT_RESULT);auto r=result(req,TRADE_RETCODE_DONE);HandleRequestTransaction(s,r);ReconcileTradeItems(s);assert(s.items[0].action==ACTION_NONE);});
check("lost result and absent PLACE remain locked through timeouts and cleanup",[]{GridState s;fresh(s);RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1);process(s);uint req=s.items[0].requestId;StartCleanup(s,"test");tick(60000);ReconcileTradeItems(s);StartCleanup(s,"test");process(s);assert(ArraySize(s.items)==1);assert(s.items[0].actionStatus==ACTION_WAIT_RESULT);assert(!CleanupFinished(s));assert(sends.size()==1);auto r=result(req,TRADE_RETCODE_TIMEOUT);HandleRequestTransaction(s,r);tick(60000);ReconcileTradeItems(s);StartCleanup(s,"test");process(s);assert(s.items[0].actionStatus==ACTION_WAIT_CONFIRM);assert(sends.size()==1);orders.push_back(Order{100});ReconcileTradeItems(s);StartCleanup(s,"test");process(s);assert(ArraySize(s.items)==2);assert(sends.size()==2);assert(sends.back().action==TRADE_ACTION_REMOVE);assert(!CleanupFinished(s));});
check("cleanup retries definitive close rejection and resolves disappearance",[]{GridState s;fresh(s);positions.push_back(Position{900,100});ReconcileTradeItems(s);StartCleanup(s,"test");process(s);auto r=result(s.items[0].requestId,TRADE_RETCODE_REJECT);HandleRequestTransaction(s,r);ReconcileTradeItems(s);StartCleanup(s,"test");process(s);assert(sends.size()==1);tick();StartCleanup(s,"test");process(s);assert(sends.size()==2);for(int n=0;n<5;n++){ReconcileTradeItems(s);StartCleanup(s,"test");process(s);}assert(sends.size()==2);positions.clear();ReconcileTradeItems(s);assert(CleanupFinished(s));ProcessCleanupState(s);assert(s.lifecycle==GRID_IDLE&&s.cycleId==1);});
check("partial close waits for matching execution history and reduced live volume",[]{GridState s;fresh(s);positions.push_back(Position{900,100});ReconcileTradeItems(s);historyDeals[500]=Deal{500,100,100,DEAL_ENTRY_IN,1.0};RequestClosePosition(s,900);process(s);auto r=result(s.items[0].requestId,TRADE_RETCODE_DONE_PARTIAL,999);HandleRequestTransaction(s,r);ReconcileTradeItems(s);assert(s.items[0].actionStatus==ACTION_WAIT_CONFIRM);assert(s.items[0].orderTicket==100);positions[0].volume=.6;Order close{999};close.status=ORDER_STATE_FILLED;close.initial=1.0;close.volume=.6;close.positionId=100;historyOrders[999]=close;historyDeals[501]=Deal{501,999,100,DEAL_ENTRY_OUT,.4};ReconcileTradeItems(s);assert(s.items[0].actionStatus==ACTION_READY);process(s);assert(sends.size()==1);tick();process(s);assert(sends.size()==2);assert(std::abs(sends.back().volume-.6)<1e-9);});
check("replace/fill race does not submit an unintended replacement",[]{GridState s;fresh(s);orders.push_back(Order{100});ReconcileTradeItems(s);assert(RequestReplaceOrder(s,100,105,2));process(s);orders.clear();Order h{100};h.status=ORDER_STATE_FILLED;historyOrders[100]=h;positions.push_back(Position{900,100});TransactionItem t;ResetTransactionItem(t);t.type=TRADE_TRANSACTION_ORDER_DELETE;t.orderTicket=100;HandleOrderTransaction(s,t);ReconcileTradeItems(s);process(s);assert(ArraySize(s.items)==1);assert(s.items[0].kind==ITEM_POSITION);assert(!s.items[0].replaceAfterDelete&&s.items[0].action==ACTION_NONE);assert(sends.size()==1);});
check("replacement requires cancellation history and starts with clean action state",[]{GridState s;fresh(s);orders.push_back(Order{100});ReconcileTradeItems(s);RequestReplaceOrder(s,100,105,2,90,120);process(s);orders.clear();ReconcileTradeItems(s);assert(s.items[0].action==ACTION_DELETE);assert(s.items[0].reconcilePending);Order h{100};h.status=ORDER_STATE_CANCELED;historyOrders[100]=h;ReconcileTradeItems(s);assert(s.items[0].action==ACTION_PLACE&&s.items[0].actionStatus==ACTION_READY);assert(s.items[0].orderTicket==0&&!s.items[0].reconcilePending&&s.items[0].attempts==0);process(s);assert(sends.size()==2);assert(sends.back().price==105&&sends.back().volume==2&&sends.back().sl==90);});
check("plain DELETE clears an unsent replacement",[]{GridState s;fresh(s);orders.push_back(Order{100});ReconcileTradeItems(s);RequestReplaceOrder(s,100,105,2);assert(RequestDeleteOrder(s,100));assert(!s.items[0].replaceAfterDelete);});
check("failed live positions are counted and absent failed items are removed",[]{GridState s;fresh(s);positions.push_back(Position{900,100});ReconcileTradeItems(s);s.items[0].action=ACTION_MODIFY_SL;s.items[0].actionStatus=ACTION_FAILED;s.items[0].requestedSL=95;ReconcileTradeItems(s);assert(CountBookPositions(s)==1);positions.clear();ReconcileTradeItems(s);assert(s.items.empty());});
check("broker scan excludes other owners, symbols and transient market orders",[]{GridState s;fresh(s);Order a{100};a.magic=88;orders.push_back(a);a.ticket=101;a.magic=77;a.symbol="OTHER";orders.push_back(a);a.ticket=102;a.symbol="TEST";a.type=ORDER_TYPE_BUY;orders.push_back(a);positions.push_back(Position{900,100,1,100,0,0,88});ReconcileTradeItems(s);assert(s.items.empty());assert(CountLiveTerminalOrders(77)==0&&CountLiveTerminalPositions(77)==0);});
check("late exact PLACE result merges recovered position after delayed source history",[]{GridState s;fresh(s);uint id=RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1,0,0,8);process(s);uint req=s.items[0].requestId;positions.push_back(Position{900,100});ReconcileTradeItems(s);assert(s.items.size()==2);Order h{100};h.status=ORDER_STATE_FILLED;historyOrders[100]=h;ReconcileTradeItems(s);assert(s.items.size()==2);auto r=result(req,TRADE_RETCODE_PLACED,100);HandleRequestTransaction(s,r);assert(s.items.size()==1);assert(s.items[0].kind==ITEM_POSITION&&s.items[0].level==8);assert(s.items[0].action==ACTION_NONE);assert(FindItemById(s,id)>=0);});
check("broker ticket change retains one position and its pending command",[]{GridState s;fresh(s);positions.push_back(Position{900,100});ReconcileTradeItems(s);RequestModifySL(s,900,90);process(s);uint id=s.items[0].id;positions[0].ticket=901;ReconcileTradeItems(s);assert(s.items.size()==1&&s.items[0].id==id);assert(s.items[0].positionTicket==901&&s.items[0].actionStatus==ACTION_WAIT_RESULT);});
check("retry exhaustion requests recovery without forging identity or cleanup",[]{GridState s;fresh(s);positions.push_back(Position{900,100});ReconcileTradeItems(s);auto t=deal(777,900);t.orderTicket=888;QueueTransaction(t);for(int n=0;n<3;n++)ProcessTransactionQueue(s,GetMicrosecondCount(),15000);assert(g_transactionQueue.empty());assert(s.lifecycle!=GRID_CLEANUP);assert(s.items[0].orderTicket==100&&s.items[0].lastDealTicket==0);assert(s.items[0].reconcilePending&&s.needsGridVerification);ReconcileTradeItems(s);assert(!s.items[0].reconcilePending);});
check("cleanup catches late objects, discards plans and enforces three in-flight requests",[]{GridState s;fresh(s);RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1);s.lifecycle=GRID_CLEANUP;RunScheduler30(s);assert(sends.empty()&&s.items.empty());for(int i=0;i<5;i++)positions.push_back(Position{(ulong)(900+i),(ulong)(100+i)});s.lifecycle=GRID_CLEANUP;RunScheduler30(s);assert(sends.size()==3);tick();RunScheduler30(s);assert(sends.size()==3);assert(!CleanupFinished(s));positions.erase(positions.begin()+4);tick();RunScheduler30(s);assert(sends.size()==4);});
check("disconnected snapshots cannot finish cleanup or send trades",[]{GridState s;fresh(s);s.lifecycle=GRID_CLEANUP;connected=false;assert(!CleanupFinished(s));orders.push_back(Order{100});RunScheduler30(s);assert(sends.empty());});
check("absence removes stable items without starting cycle cleanup; pause survives reset",[]{GridState s;fresh(s);orders.push_back(Order{100});ReconcileTradeItems(s);s.mode=MODE_PAUSED;orders.clear();for(int n=0;n<3;n++)ReconcileTradeItems(s);assert(s.items.empty()&&s.lifecycle==GRID_IDLE);assert(s.mode==MODE_PAUSED);});
check("snapshot adopts missed events with no synthetic strategy commands",[]{GridState s;fresh(s);orders.push_back(Order{100});positions.push_back(Position{900,101});ReconcileTradeItems(s);assert(s.items.size()==2);for(auto &i:s.items)assert(i.action==ACTION_NONE&&i.actionStatus==ACTION_IDLE);});
check("reverse send traversal handles adjacent already-absent targets",[]{GridState s;fresh(s);orders.push_back(Order{100});orders.push_back(Order{101});ReconcileTradeItems(s);RequestDeleteOrder(s,100);RequestDeleteOrder(s,101);orders.clear();process(s);assert(s.items.empty()&&sends.empty());});
check("same-price request-add order does not unlock unrelated PLACE",[]{GridState s;fresh(s);RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1);process(s);uint req=s.items[0].requestId;Order o{100};o.status=ORDER_STATE_REQUEST_ADD;orders.push_back(o);ReconcileTradeItems(s);int plan=FindItemByRequestId(s,req);assert(plan>=0&&s.items[plan].actionStatus==ACTION_WAIT_RESULT&&s.items[plan].orderTicket==0);orders[0].status=ORDER_STATE_PLACED;ReconcileTradeItems(s);plan=FindItemByRequestId(s,req);assert(plan>=0&&s.items[plan].actionStatus==ACTION_WAIT_RESULT&&s.items[plan].orderTicket==0);assert(sends.size()==1);});
check("filled order with delayed position visibility cannot finish cleanup",[]{GridState s;fresh(s);RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1);process(s);auto r=result(s.items[0].requestId,TRADE_RETCODE_DONE,100);HandleRequestTransaction(s,r);Order h{100};h.status=ORDER_STATE_FILLED;historyOrders[100]=h;historyDeals[500]=Deal{500,100,100};StartCleanup(s,"test");for(int n=0;n<10;n++){tick(5000);ReconcileTradeItems(s);StartCleanup(s,"test");}assert(s.items.size()==1&&!CleanupFinished(s));assert(s.items[0].actionStatus==ACTION_WAIT_CONFIRM);positions.push_back(Position{900,100});ReconcileTradeItems(s);StartCleanup(s,"test");process(s);assert(sends.back().action==TRADE_ACTION_DEAL);});
check("rapid open then close is resolved by position history without phantom item",[]{GridState s;fresh(s);RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1);process(s);auto r=result(s.items[0].requestId,TRADE_RETCODE_DONE,100);HandleRequestTransaction(s,r);Order h{100};h.status=ORDER_STATE_FILLED;historyOrders[100]=h;historyDeals[500]=Deal{500,100,100};historyDeals[501]=Deal{501,101,100,DEAL_ENTRY_OUT};StartCleanup(s,"test");for(int n=0;n<3;n++)ReconcileTradeItems(s);assert(s.items.empty()&&CleanupFinished(s));});
check("startup rejects invalid scheduling and incompatible account modes",[]{GridState s;fresh(s);InpSchedulerBudgetMs=0;assert(OnInit()==INIT_PARAMETERS_INCORRECT);InpSchedulerBudgetMs=15;accountMode=0;assert(OnInit()==INIT_FAILED);accountMode=ACCOUNT_MARGIN_MODE_RETAIL_HEDGING;fifo=true;assert(OnInit()==INIT_FAILED);fifo=false;assert(OnInit()==INIT_SUCCEEDED);});
check("shared budget stops submissions and queue frame cap is honored",[]{GridState s;fresh(s);RequestPlacePending(s,ORDER_TYPE_BUY_STOP,100,1);ProcessPendingActions(s,mock_us-16000,15000);assert(sends.empty());TransactionItem t;ResetTransactionItem(t);t.type=TRADE_TRANSACTION_ORDER_ADD;t.orderTicket=100;for(int i=0;i<40;i++)QueueTransaction(t);ProcessTransactionQueue(s,GetMicrosecondCount(),15000);assert(ArraySize(g_transactionQueue)-g_transactionHead==8);});
check("canceling a partially filled remainder preserves the requested replacement",[]{GridState s;fresh(s);Order o{100};o.volume=.6;orders.push_back(o);positions.push_back(Position{900,100,.4});ReconcileTradeItems(s);assert(s.items.size()==2);assert(RequestReplaceOrder(s,100,105,.6));process(s);orders.clear();o.status=ORDER_STATE_CANCELED;historyOrders[100]=o;ReconcileTradeItems(s);assert(s.items.size()==2);assert(CountBookPositions(s)==1);int replacement=-1;for(int i=0;i<ArraySize(s.items);i++)if(s.items[i].action==ACTION_PLACE)replacement=i;assert(replacement>=0&&s.items[replacement].requestedLot==.6);process(s);assert(sends.size()==2&&sends.back().action==TRADE_ACTION_PENDING);});
check("replacement still follows an expired unfilled old order",[]{GridState s;fresh(s);orders.push_back(Order{100});ReconcileTradeItems(s);RequestReplaceOrder(s,100,105,1);orders.clear();Order h{100};h.status=ORDER_STATE_EXPIRED;historyOrders[100]=h;ReconcileTradeItems(s);assert(s.items.size()==1&&s.items[0].action==ACTION_PLACE);});
std::cout<<passed<<" scenario groups passed\n";
}
